version: '3.4'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # app:
  #   build: server/
  #   env_file: server/.env
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #   command: bash -c "bin/manage migrate && pipenv run uwsgi"
  #   volumes:
  #     - ./server:/ets

  server:
    build: server/
    ports:
      - 8001:80
    volumes:
      - ./server:/var/www/html
      # - ./config:/usr/local/etc/php

volumes:
  database:
    driver: local
